var quotes = [
    '"Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me."',
    '"Guess what, I have flaws. What are they? Oh I don\’t know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I\’ll hit somebody with my car. So sue me."',
    '"Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it\’s not like this compulsive need to be liked, like my need to be praised."',
    '"You know what they say: \'Fool me once, strike one, but fool me twice…strike three.\'"',
    '"I\’m not superstitious but I am a little stitious.”',
    '"There\’s no such thing as an appropriate joke. That\’s why it’s called a joke."',
    '"I need a username. And I have a great one. Little Kid Lover. That way people will know exactly where my priorities are at."',
    '"Hi, I’m Date Mike. Nice to meet me. How do you like your eggs in the morning?"',
    '"I guess the attitude that I’ve tried to create here is that I’m a friend first and a boss second and probably an entertainer third."',
    '"I am Michael, and I am part English, Irish, German, and Scottish…sort of a virtual United Nations."',
    '"If you break that girl’s heart, I will kill you. That’s just a figure of speech. But seriously, if you break that girl’s heart, I will literally kill you and your entire family."',
    '"Don\’t ever, for any reason, do anything for anyone, for any reason, ever, no matter what. No matter where. Or who, or who you are with, or where you are going or… or where you’ve been… ever. For any reason, whatsoever."',
    '"Abraham Lincoln once said that, ‘If you’re a racist, I will attack you with the North.’ And those are the principles that I carry with me in the workplace."',
    '"Well, well, well, how the turntables."',
    '"You cheated on me? When I specifically asked you not to?"',
    '"I don’t want any special treatment, Pam. I just want you to treat me like you would some family member who’s undergone some sort of serious physical trauma. I don\’t think that\’s too much to ask?"',
    '"It\’s a good thing Russia doesn’t exist anymore."',
    '"Sometimes I’ll start a sentence and I don\’t even know where it’s going. I just hope I find it along the way."',
    '"The worst thing about prison was the Dementors."',
    '"Wikipedia is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information."',
    '"I don\’t understand. We have a day honoring Martin Luther King, but he didn\’t even work here."',
    '"And I knew exactly what to do. But in a much more real sense, I had no idea what to do."',
    '"Well, it\’s love at first sight. Actually, it was … No, it was when I heard her voice. It was love at first see with my ears."',
    '"That\’s what she said."',
    '"Webster\'s Dictionary defines wedding as: The fusing of two metals with a hot torch."',
    '"I feel like all my kids grew up, and then they married each other. It\'s every parents\' dream."',
    '"St. Patrick\'s Day is the closest thing the Irish have to Christmas."',
    '"When the son of the deposed king of Nigeria emails you directly, asking for help, you help! His father ran the freaking country! Ok?"',
    '"I am running away from my responsibilities. And it feels good."',
    '"Society teaches us that having feelings and crying is bad and wrong. Well, that\'s baloney, because grief isn\'t wrong. There\'s such a thing as good grief. Just ask Charlie Brown."',
    '"I\'m an early bird and I\'m a night owl. So I\'m wise and I have worms."',
    '"I love my employees even though I hit one of you with my car."',
    '"Is there a God? If not, what are all these churches for? And who is Jesus\' dad?"',
    '"No, I\’m not going to tell them about the downsizing. If a patient has cancer, you don\’t tell them."',
    '"Make friends first, make sales second, make love third. In no particular order."',
    '"It\’s not like booze ever killed anyone."',
    '"Friends joke with one another. \'Hey, you’re poor.\' \'Hey, your momma’s dead.\' That\’s what friends do."',
    '"It just seems awfully mean. But sometimes, the ends justify the mean."',
    '"An office is for not dying. An office is a place to live life to the fullest, to the max, to… An office is a place where dreams come true."',
    '"I say dance, they say ‘How high?’"',
     '"Toby is in HR which technically means he works for corporate. So, he\’s not really a part of our family. Also, he’s divorced… so he\’s not really a part of his family."',
    '"People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake. And to me the choice is easy."',
    '"I don\’t come up with this stuff, I just forward it along. You wouldn\’t arrest the guy who was just passing drugs from one guy to another."',
    '"My mind is going a mile an hour."',
    '"I would not miss it for the world. But if something else came up I would definitely not go."',
    '"They say that your wedding day goes by in such a flash that you\’re lucky if you even get a piece of your own cake. I say that\’s crazy. I say let them eat cake. Margaret Thatcher said that about marriage. Smart broad."',
    '"Two weeks ago, I was in the worst relationship of my life. She treated me poorly, we didn\’t connect, I was miserable. Now, I am in the best relationship of my life, with the same woman. Love is a mystery."',
    '"Here it is, heart of New York City, Times Square… named for the good times you have when you\’re in it."',
    '"When I was five, I imagined that there was such a thing as a unicorn. And this was before I had even heard of one or seen one. I just drew a picture, of a horse, that could fly over rainbows, and a had a huge spike in its head. I was five! Five-years-old. Couldn\’t even talk yet."',
    '"I saved a life. My own. Am I a hero? … I really can\’t say, but yes!"',
    '"The most sacred thing I do is care and provide for my workers, my family. I give them money. I give them food. Not directly, but through the money."',
    '"Now, you may look around and see two groups here. White collar, blue collar. But I don\’t see it that way. And you know why not? Because I am collar-blind."',
    '"I would say I kind of have an unfair advantage, because I watch reality dating shows like a hawk, and I learn. I absorb information from the strategies of the winners and the losers. Actually, I probably learn more from the losers."',
    '"Pizza: the great equalizer."',
    '"Any man who says he totally understands women is a fool. Because they are un-understandable."',
    '"Presents are the best way to show someone how much you care. It’s like this tangible thing that you can point to and say, \'Hey, man, I love you this many dollars worth.\'"',
    '"Sometimes you have to take a break from being the kind of boss that’s always trying to teach people things. Sometimes you just have to be the boss of dancing."',
    '"Reverse psychology is an awesome tool. I don\’t know if you guys know about it, but basically, you make someone think the opposite of what you believe. And that tricks them into doing something stupid. Works like a charm."'
    
]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}